export const CREATE_DISH_REQUEST = 'CREATE_DISH_REQUEST';
export const CREATE_DISH_SUCCESS = 'CREATE_DISH_SUCCESS';
export const CREATE_DISH_FAILED = 'CREATE_DISH_FAILED';

export const GET_DISHES = 'GET_DISHES';
