export const CREATE_DISH_REQUEST = 'CREATE_DISH_REQUEST';
export const CREATE_DISH_SUCCESS = 'CREATE_DISH_SUCCESS';
export const CREATE_DISH_FAILED = 'CREATE_DISH_FAILED';

export const GET_STORE_DISHES_REQ = 'GET_STORE_DISHES_REQ';
export const GET_STORE_DISHES_FAILED = 'GET_STORE_DISHES_FAILED';
export const GET_STORE_DISHES_SUCCESS = 'GET_STORE_DISHES_SUCCESS';
